#!/bin/bash
../bin/draw_warp_tracks ../log/png/gray_anaglyph/csiegirl/ ../log/txt/tracks_along/csiegirl_r.tracks ../log/txt/path_joint/csiegirl_s+u_1e0_d+a_1e-1_r.path ../log/png/tracks/csiegirl_length_20_r.png ../log/png/tracks/csiegirl_purposed_length_20_r.png 20 163 ../log/png/gray_anaglyph/csiegirl/csiegirl_proposed_blank_0163.png
../bin/draw_warp_tracks ../log/png/gray_anaglyph/csiegirl/ ../log/txt/tracks_along/csiegirl_r.tracks ../log/txt/path_along/csiegirl_s+u_1e1_r.path ../log/png/tracks/csiegirl_length_20_r.png ../log/png/tracks/csiegirl_iccv09_length_20_r.png 20 163 ../log/png/gray_anaglyph/csiegirl/csiegirl_iccv_blank_0163.png
../bin/draw_warp_tracks ../log/png/gray_anaglyph/csiegirl/ ../log/txt/tracks_along/csiegirl_r.tracks ../log/txt/path_deshaker/csiegirl_deshaker_r.path ../log/png/tracks/csiegirl_length_20_r.png ../log/png/tracks/csiegirl_deshaker_length_20_r.png 20 163 ../log/png/gray_anaglyph/csiegirl/csiegirl_deshaker_blank_0163.png
#../bin/draw_warp_tracks ../log/png/gray_anaglyph/csiegirl/ ../log/txt/tracks_along/csiegirl_r.tracks ../log/txt/path_joint/csiegirl_s+u_1e0_d+a_1e-1_r.path ../log/png/tracks/csiegirl_length_20_r.png ../log/png/tracks/csiegirl_purposed_length_20_r.png 20 163
#../bin/draw_warp_tracks ../dat/img/children_l/ ../log/txt/tracks_along/children_l.tracks ../log/txt/path_joint/children_s+u_1e0_d+a_1e-1_l.path ../log/png/tracks/children_purposed_length_20_l.png ../log/png/tracks/children_purposed_length_20_w_l.png 20 0
#../bin/draw_warp_tracks ../dat/img/children_r/ ../log/txt/tracks_along/children_r.tracks ../log/txt/path_joint/children_s+u_1e0_d+a_1e-1_r.path ../log/png/tracks/children_purposed_length_20_r.png ../log/png/tracks/children_purposed_length_20_w_r.png 20 0
#../bin/draw_warp_tracks ../dat/img/redgirl_l/ ../log/txt/tracks_along/redgirl_l.tracks ../log/txt/path_joint/redgirl_s+u_1e0_d+a_1e-1_l.path ../log/png/tracks/redgirl_purposed_length_20_l.png ../log/png/tracks/redgirl_purposed_length_20_w_l.png 20 251
#../bin/draw_warp_tracks ../dat/img/redgirl_r/ ../log/txt/tracks_along/redgirl_r.tracks ../log/txt/path_joint/redgirl_s+u_1e0_d+a_1e-1_r.path ../log/png/tracks/redgirl_purposed_length_20_r.png ../log/png/tracks/redgirl_purposed_length_20_w_r.png 20 251 
